version: 0.2

phases:
    install:
        commands:
            - echo npm install yarn -g started on `date`
            - npm install yarn -g
            - echo npm install yarn -g started on `date`
    pre_build:
        commands:
            - echo `pwd`
            - echo yarn INSTALL started on `date`
            - yarn install
            - echo yarn INSTALL completed on `date`
    build:
        commands:
            - echo `pwd`
            
            - echo yarn TEST started on `date`
            - cd packages/server
            - yarn test
            - cd ../..
            - echo yarn TEST completed on `date`
            
            - echo BUILD started on `date`
            - yarn run build
            - echo BUILD completed on `date`
            
artifacts:
    files:
        - '**/*'
cache:
    paths:
        - 'node_modules/**/*'
        - 'packages/admin/node_modules/**/*'
        - 'packages/client/node_modules/**/*'
        - 'packages/server/node_modules/**/*'
