export * from './star-info-page/star-info-page.component';
export * from './stars-page/stars-page.component';
export * from './star-dances-list/star-dances-list.component';
export * from './star-dance-figures-page/star-dance-figures-page.component';
export * from './star-figures-list/star-figures-list.component';
export * from './star-figure-page/star-figure-page.component';
export * from './star-pages-navigation-bar/star-pages-navigation-bar.component';
export * from './star-skills/star-skills.component';
export * from './star-skills/star-skill-view/star-skill-view.component';
