export enum Errors {
    INVALID_MONGO_ID = "INVALID_ID",
    MAIL_ALREADY_EXISTS = "MAIL_ALREADY_EXISTS",
    ALREADY_VERIFIED = "ALREADY_VERIFIED",
    MAIL_NOT_EXISTS = "MAIL_NOT_EXISTS",
    NON_EXISTING_USER = "NON_EXISTING_USER",
    INVALID_EMAIL = "INVALID_EMAIL",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    PASSWORD_MISMATCH = "PASSWORD_MISMATCH",
    TOKEN_MISMATCH = "TOKEN_MISMATCH",
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
    INVALID_VERIFY_TOKEN = "INVALID_VERIFY_TOKEN",
    INVALID_EMAIL_TOKEN = "INVALID_EMAIL_TOKEN",
}
